version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - /Users/Example/Desktop/WordPress/db/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress # Dont Change
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress:latest
     ports:
       - 8570:80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306  # Dont Change
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
      - /Users/Example/Desktop/WordPress/youcandlesnew
